# Generated by Django 4.0.2 on 2022-04-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacoesArquivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=100)),
                ('tamanho_arquivo', models.CharField(max_length=100)),
                ('data_importacao_arquivo', models.DateTimeField(auto_now_add=True)),
                ('data_transacao_arquivo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=255)),
                ('agencia_origem', models.CharField(max_length=255)),
                ('conta_origem', models.CharField(max_length=255)),
                ('banco_destino', models.CharField(max_length=255)),
                ('agencia_destino', models.CharField(max_length=255)),
                ('conta_destino', models.CharField(max_length=255)),
                ('valor_da_transacao', models.FloatField()),
                ('data_da_transacao', models.DateField()),
                ('hora_da_transacao', models.CharField(max_length=255)),
                ('id_arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacoes.importacoesarquivos')),
            ],
        ),
    ]
