# Generated by Django 4.0.2 on 2022-04-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_importacoesarquivos_usuario_importacao_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacoesarquivos',
            name='status_usuario',
            field=models.BooleanField(default=True),
        ),
    ]
