# Generated by Django 4.0.2 on 2022-04-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0003_importacoesarquivos_status_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacoesarquivos',
            name='status_usuario',
        ),
    ]
