# Generated by Django 4.0.1 on 2022-04-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0005_filtro_buscas_analises'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filtro_Buscas_Analises',
        ),
    ]
