# Generated by Django 4.0.2 on 2022-04-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0006_delete_filtro_buscas_analises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta_Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_poupança', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacoes.controller')),
            ],
        ),
    ]
