# Generated by Django 4.0.2 on 2022-04-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0007_conta_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta_controller',
            name='agencia',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conta_controller',
            name='banco',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conta_controller',
            name='conta',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conta_controller',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
