# Generated by Django 4.0.2 on 2022-04-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0008_conta_controller_agencia_conta_controller_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta_controller',
            name='agencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conta_controller',
            name='banco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conta_controller',
            name='conta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
