# Generated by Django 4.0.2 on 2022-04-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0009_alter_conta_controller_agencia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conta_Controller',
        ),
    ]
