# Generated by Django 4.0.2 on 2022-05-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0011_contacorrente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContaCorrente',
        ),
    ]
