# Generated by Django 4.0.2 on 2022-05-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0012_delete_contacorrente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='valor_da_transacao',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
