# Generated by Django 4.0.2 on 2022-05-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0013_alter_controller_valor_da_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='valor_da_transacao',
            field=models.FloatField(),
        ),
    ]
